### ISSUE TITLE
RuntimeError: cublas runtime error : library not initialized at

### ISSUE THREAD

**Issue by HamHyungkyu** [gpgpu-sim/gpgpu-sim_distribution#177]
Hello, I'm trying to run a simple pytorch code on pytorch-gpgpu-sim, but I met this problem..
```import torch
x = torch.randn(10,10, device="cuda:0")
y = torch.randn(10,10, device="cuda:0")
z = torch.matmul(x, y)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cublas runtime error : library not initialized at  /home/user/pytorch-gpgpu-sim/aten/src/THC/THCGeneral.cpp:333
```
Also I met this kind of problem in different code.
`RuntimeError: CuDNN error: CUDNN_STATUS_NOT_INITIALIZED`

Does anyone know why these problems occur?

My env is
centos 7
python 3.6.9
gcc 5.4.0
CUDA 8.0
CUDNN 7.1
PYTORCH_BIN = /home/user/pytorch-gpgpu-sim/torch/lib/libcaffe2_gpu.so
TITANV config

**Comment by cng123** [comment]
Hi,

Could you try running the above code on hardware with a fully updated pytorch (reinstall from pip)? It may be possible that one of the solutions in https://github.com/torch/cutorch/issues/677 could fix the issue.

If the above does not fix the problem, could you attach the full output log of the script? Also, if possible, could you post your environmental variables, as well as the output log from building pytorch?

**Comment by Wen-Tian-Pineapple** [comment]
> Hello, I'm trying to run a simple pytorch code on pytorch-gpgpu-sim, but I met this problem..
> 
> ```
> x = torch.randn(10,10, device="cuda:0")
> y = torch.randn(10,10, device="cuda:0")
> z = torch.matmul(x, y)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> RuntimeError: cublas runtime error : library not initialized at  /home/user/pytorch-gpgpu-sim/aten/src/THC/THCGeneral.cpp:333
> ```
> 
> Also I met this kind of problem in different code. `RuntimeError: CuDNN error: CUDNN_STATUS_NOT_INITIALIZED`
> 
> Does anyone know why these problems occur?
> 
> My env is centos 7 python 3.6.9 gcc 5.4.0 CUDA 8.0 CUDNN 7.1 PYTORCH_BIN = /home/user/pytorch-gpgpu-sim/torch/lib/libcaffe2_gpu.so TITANV config

@HamHyungkyu Hello,
Did you find a way to bypass this issue? I had the same library not initialized problem and couldn't fix it, I tried link static library but I got some other bugs. Thanks!
